baseURL = "https://leondramendoza.github.io/"
languageCode = "en-us"
title = "Leondra Mendoza"
theme = "PaperMod"
buildFuture = true

[pagination]
pagerSize = 10

[params]
ShowReadingTime = true
ShowShareButtons = true
ShowPostNavLinks = true
ShowBreadCrumbs = true